MODEL_PATH = 'data/model/'  # каталог модели
CACHE_PATH = 'data/model/model_cache'  # каталог кэша
SOURCE_DATA_PATH = "data/dataset/geo-reviews-dataset-2023.tskv"  # путь к исходным данным
RAW_DATA_PATH = "data/dataset/geo_reviews_raw.json"  # путь к сырым данным после парсера
CLEANED_DATA_PATH = "data/dataset/geo_reviews_cleaned.json"  # путь к данным после очистки
MODEL_NAME = 'ai-forever/rugpt3small_based_on_gpt2'  # используемая модель
DATASETS_PATH = 'data/dataset'  # путь к каталогу датасетов
CLEANED_DATA_FILE = 'geo_reviews_cleaned.json'  # имя файла очищенных данных
OUTPUT_MODEL_NAME = 'fine_tuned_geo_reviews_model'  # имя модели после обучения
BALANCED_DATA_PATH = 'data/dataset/geo_reviews_balanced.json'  # путь к сбалансированным данным
NORMALIZED_DATA_PATH = 'data/dataset/geo_reviews_normalized.json'
